package com.commercehub.repository;

import java.math.BigDecimal;
import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import com.commercehub.entity.OrderItem;
import com.commercehub.util.OrderStatus;

@Repository
public interface OrderItemRepository extends JpaRepository<OrderItem, Long>, JpaSpecificationExecutor<OrderItem> {
	
    /**
     * Find all order items for a specific order
     * 
     * @param orderId the order identifier
     * @return list of order items for the specified order
     */
	List<OrderItem> findByOrderId(Long orderId);
	
    /**
     * Find all order items for a specific product
     * 
     * @param productId the product identifier
     * @return list of order items containing the specified product
     */
	List<OrderItem> findByProductId(Long productId);
	
	/**
     * Count order items for a specific order
     * 
     * @param orderId the order identifier
     * @return count of order items in the order
     */
	Long countByOrderId(Long orderId);
	
	/**
     * Check if a product exists in any order
     * 
     * @param productId the product identifier
     * @return true if product exists in any order, false otherwise
     */
	boolean existsByProductId(Long productId);
	
    /**
     * Delete all order items for a specific order
     * 
     * @param orderId the order identifier
     */
	void deleteByOrderId(Long orderId);
	
    /**
     * Get total quantity sold for a specific product
     * 
     * @param productId the product identifier
     * @return total quantity sold
     */
	@Query("Select coalesce(Sum(oi.quantity),0) From OrderItem oi Where oi.product.id = :productId")
	Long gettotalQuantitySoldByProductId(@Param("productId") Long productId);
	
    /**
     * Get total revenue for a specific product
     * 
     * @param productId the product identifier
     * @return total revenue generated by the product
     */
	@Query("Select coalesce(Sum(oi.totalPrice),0) From OrderItem oi Where oi.product.id = :productId")
	BigDecimal getTotalRevenueByProductId(@Param("productId") Long productId);
	
    /**
     * Find order items by product and order status
     * 
     * @param productId the product identifier
     * @param status the order status
     * @return list of order items matching the criteria
     */
	@Query("Select oi From OrderItem oi Join oi.order o Where oi.product.id = :productId And o.orderStatus = :orderStatus")
	List<OrderItem> findByProductIdAndOrderStatus(@Param("productId") Long productId, @Param("orderStatus") OrderStatus orderStatus);
	
	/**
     * Find top selling products
     * 
     * @param limit the maximum number of products to return
     * @return list of product IDs and their total quantities sold
     */
	@Query("Select oi.product.id, Sum(oi.quantity) as totalQuantity From OrderItem oi "
			+ "Group By oi.product.id "
			+ "Order by totalQuantity Desc")
	List<Object[]> findTopSellingProducts();

}
